"""Build a compact text-glyph font from pinned STIX; no font tooling runs in the extension.

Usage: python scripts/build-epub-math-font.py /path/to/STIXTwoMath-Regular.otf
Source: stipub/stixfonts tag v2.13b171, fonts/static_otf/STIXTwoMath-Regular.otf.
Requires fonttools. The original OFL/copyright is preserved; the derived font
is renamed PlumePilot Math. MATH assembly tables are unused by XHTML text;
fractions and other two-dimensional notation remain PDF-derived images.
"""
from pathlib import Path
import hashlib, json, sys, unicodedata
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1])
assert hashlib.sha256(source.read_bytes()).hexdigest() == '3a5f3f26f40d5698b3c62dd085d48d6663696a3f80825aab8b553d5097518e8c'
font = TTFont(source, recalcTimestamp=False)
blocks = [(0x370, 0x3ff), (0x1f00, 0x1fff), (0x2070, 0x22ff),
    (0x2308, 0x230b), (0x27c0, 0x27ef), (0x2900, 0x2aff), (0x1d400, 0x1d7ff)]
points = [point for point in font.getBestCmap() if unicodedata.category(chr(point)) == 'Sm'
    or any(first <= point <= last for first, last in blocks)]
options = subset.Options()
options.drop_tables += ['MATH']
options.name_IDs = ['*']
options.name_legacy = True
options.name_languages = ['*']
options.layout_features = ['*']
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=points)
subsetter.subset(font)
for name in font['name'].names:
    if name.nameID in [1, 3, 4, 6, 16, 21]:
        value = 'PlumePilotMath-Regular' if name.nameID == 6 else 'PlumePilot Math'
        name.string = value.encode(name.getEncoding())
font['CFF '].cff.fontNames = ['PlumePilotMath-Regular']
top = font['CFF '].cff.topDictIndex[0]
top.FamilyName = 'PlumePilot Math'
top.FullName = 'PlumePilot Math'
output = root / 'assets/fonts/plumepilot-math.otf'
font.save(output)
points = sorted(TTFont(output).getBestCmap())
ranges = []
for point in points:
    if ranges and point == ranges[-1][1] + 1:
        ranges[-1][1] = point
    else:
        ranges.append([point, point])
(root / 'epub-math-coverage.mjs').write_text(
    '// PlumePilot Math (STIX Two Math v2.13b171 subset). Generated by scripts/build-epub-math-font.py.\n'
    '// Actual glyph coverage; mathematical symbols are not normalized.\n'
    'export const mathFontRanges = ' + json.dumps(ranges, indent=2) + ';\n')
print(f'{output.name}: {output.stat().st_size} bytes; SHA-256 {hashlib.sha256(output.read_bytes()).hexdigest()}')
